version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "A first Hello !"
      - run: pip install --user -q --no-cache-dir -r requirements.txt
      - run: python -m flake8 src/* tests/*
      - run: PYTHONPATH="src:src/etl:src/helpers:src/deploy:src/lambda_code" python -m pytest